### ISSUE TITLE
All Grammars

### ISSUE THREAD

**Issue by kucukkanat** [code-hike/bright#1]
Just out of curiosity, 
Did you create all-grammars by yourself or is it a collection that you took from some other source ?
https://github.com/code-hike/bright/blob/main/packages/bright/src/all-grammars.js

**Comment by pomber** [comment]
Grammars come from shiki's repo:

https://github.com/code-hike/bright/blob/bc7130d4dd394c6d632d73203c7995e7fb4efd40/web/pages/api/grammars.js#L4

And shiki gets them from a couple of different places
