### ISSUE TITLE
Using Bright with Markdoc

### ISSUE THREAD

**Issue by drusellers** [code-hike/bright#11]
I'm currently using [Markdoc](https://markdoc.dev/) to pregenerate markdown on the server. I'm curious if I could use this library to process my code blocks. Would it be possible to get a sample of calling the library outside of JSX?

**Comment by pomber** [comment]
Hi, I haven't tried Markdoc, but if it works with React Server Components it should be possible to use it. 

I found this starter https://github.com/dylanmeivis/nextjs13-starter-markdoc from @dylanmeivis using the Next app directory (which defaults to server components). Maybe you can try that and let me know if it works.

**Comment by drusellers** [comment]
I'm using an html generation step, so I was thinking that I could maybe hook Bright into that. I can easily use it as a RSC for sure in other parts - but was thinking of hooking it into my CMS generation step. No worries. :)
