### ISSUE TITLE
`parseChildren` throws when className is undefined (occurring with next-mdx-remote)

### ISSUE THREAD

**Issue by MaxLeiter** [code-hike/bright#12]
Code sandbox: https://codesandbox.io/p/sandbox/gifted-jepsen-e89kcj?file=%2Fapp%2Fpage.tsx&selection=%5B%7B%22endColumn%22%3A19%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A9%2C%22startLineNumber%22%3A9%7D%5D

<details>
<summary> <code>className</code> bug (fixed in v0.7.1)</summary>
 
I'm encountering a problem with `next-mdx-remote/rsc` when I don't have a language specified in my codeblocks.

The failure is [here](https://github.com/code-hike/bright/blob/1bae07b7551a48d0d3793b0a2ed7a74349785dce/lib/src/index.tsx#L183) because `className` is not defined: https://github.com/code-hike/bright/blob/1bae07b7551a48d0d3793b0a2ed7a74349785dce/lib/src/index.tsx#L183

Some console.logs have shown me there is no `className` if no language is passed.
</details>

There's also a type error with `next-mdx-remote`'s `components["pre"]` type and the `Code` type from this lib (separate from the element being a promise/RSC):

```

Type bug with next-mdx-remote:

(property) pre?: keyof JSX.IntrinsicElements | Component<DetailedHTMLProps<HTMLAttributes<HTMLPreElement>, HTMLPreElement>> | undefined
Type 'CodeComponent' is not assignable to type 'keyof IntrinsicElements | Component<DetailedHTMLProps<HTMLAttributes<HTMLPreElement>, HTMLPreElement>> | undefined'.
  Type 'CodeComponent' is not assignable to type 'FunctionComponent<DetailedHTMLProps<HTMLAttributes<HTMLPreElement>, HTMLPreElement>>'.
    Types of parameters 'props' and 'props' are incompatible.
      Type 'ClassAttributes<HTMLPreElement> & HTMLAttributes<HTMLPreElement>' is missing the following properties from type '{ style?: CSSProperties | undefined; title?: string | undefined; Pre: (brightProps: { code: string; style?: CSSProperties | undefined; title?: string | undefined; ... 17 more ...; subProps?: Partial<...>[] | undefined; }) => Element; ... 14 more ...; code?: string | undefined; }': Pre, Root, TitleBarContent, Tab, and 4 more.
```

I'm not sure on the correct types, but something seems off here and I feel like `JSX.Element` or `ReactNode` and utils like `React.PropsWithChildren` should be used. I'll open a PR soon with a quick fix for my problem. I guess another alternative is default the lang to `plaintext` (and add support for that to the relevant upstream)

**Comment by pomber** [comment]
Hi, thanks for reporting the issue.

So there are 3 issues here:
- The type 'CodeComponent' not being assignable to the typeof `pre` from next-mdx-remote
- MDX codeblocks without a language are failing because of `className` not being defined (your PR #13 is fixing this)
- MDX codeblocks without a language should be "highlighted" as plaintext (I should fix https://github.com/code-hike/lighter/issues/5 first)

**Comment by pomber** [comment]
Try v0.7.1. It should fix the codeblock without lang (but not the type error).

**Comment by MaxLeiter** [comment]
v0.7.1 fixed that error. Thank you!
