### ISSUE TITLE
Custom theme names don't work

### ISSUE THREAD

**Issue by altano** [code-hike/bright#16]
Thanks for this amazingly easy to use library!

I'm having one issue which is that themes don't seem to work when I give them custom  names. I'm trying to use this with Next.js.

mdx-components.tsx:
```typescript
// ❌ doesn't work ❌
Code.theme = {
  "eighties": "dracula", // and corresponding data-theme="eighties"
  "nineties": "solarized-light",
};

export function useMDXComponents(components: MDXComponents): MDXComponents {
  return {
    ...components,
    pre: Code,
  };
}
```

But if I use dark/light it works fine:

mdx-components.tsx:
```typescript
// ✅ works ✅
Code.theme = {
  dark: "dracula", // and corresponding data-theme="dark"
  light: "solarized-light",
};

export function useMDXComponents(components: MDXComponents): MDXComponents {
  return {
    ...components,
    pre: Code,
  };
}
```

If I try the former and not the latter, I don't get theming (my code blocks have a dark background and light text with no syntax highlighting).

Is this expected and I'm just misunderstanding the docs?

**Comment by pomber** [comment]
Yes, it's working as expected (but I should improve the docs), you can only use `dark` and `light`. Why do you need different names? Is it to use more than two themes?

**Comment by altano** [comment]
Ah, got it, thanks. My site currently only has two themes so that works for me. There’s an 80s and a 90s theme. One just happens to be dark and the other light so it’s not even a huge stretch to just use those names, it’s fine. Thanks!

**Comment by pomber** [comment]
I considered making it more flexible but guessed that most people only need dark/light, and the extra complexity wasn't worth it. Also, if really needed, it can be done in userland.
