### ISSUE TITLE
Custom theme doc improvement

### ISSUE THREAD

**Issue by altano** [code-hike/bright#17]
I don't know how [the docs](https://github.com/code-hike/bright/blob/69b7701bf2ef9f4536d63518967bd60448b85729/web/app/page.js#L431-L439) are styled so I'm just going to suggest the improvement here.

Instead of the current docs for "Custom Theme":

```js
Code.theme = {
  name: "myTheme"
}
```

It might be helpful to mention that you import the theme and pass that in, instead of a theme name, e.g.:

```js
import myCustomTheme from "my-custom-theme.json";
Code.theme = myCustomTheme;
```

**Comment by pomber** [comment]
You are right, the import makes it easier to understand. I'll update it (and make the docs more approachable)

**Comment by pomber** [comment]
Fixed

![image](https://user-images.githubusercontent.com/1911623/235301284-719721e4-4857-4754-86c6-c644d4ac64a8.png)
