### ISSUE TITLE
Uses NodeJS APIs and therefore incompatible with Vercel Edge

### ISSUE THREAD

**Issue by lzrscg** [code-hike/bright#20]
```
../../node_modules/@code-hike/lighter/dist/browser.esm.mjs:16:24
Module not found: Can't resolve 'https'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
../../node_modules/bright/dist/index.mjs
```

I haven't had time to put together a demo to easily replicate. I will try to do this if it would be helpful, but thought I should just submit this issue to put it on your radar as soon as possible nonetheless.

# Why this is happening?
> Some Node.js APIs other than the ones listed above are not supported. For example, you can't read or write to the filesystem
https://vercel.com/docs/concepts/functions/edge-functions/edge-runtime#unsupported-apis

([Https](https://nodejs.org/api/https.html) is not listed)

**Comment by pomber** [comment]
That's during build, right? We only import `https` if `fetch` is not available. So, during runtime it shouldn't fail, do you know if it's possible to tell the build to stop eagerly checking the modules?

**Comment by lzrscg** [comment]
Hey sorry for the slow response, been traveling. I'll put more info together for how to replicate.

This definitely was a runtime issue. The error showed up in the browser after visiting an Edge page with bright embedded.

**Comment by pynchmeister** [comment]
Hey, here is an example:

https://codesandbox.io/p/sandbox/bitter-cloud-lk9r5z?file=%2Fapp%2Fpage.tsx%3A29%2C31

**Comment by pomber** [comment]
Depends on https://github.com/code-hike/lighter/issues/19

**Comment by pomber** [comment]
> Hey, here is an example:

Thanks.

Fix depends on https://github.com/code-hike/lighter/issues/19

**Comment by pomber** [comment]
`v0.8.3` should fix this. Here's @pynchmeister codesandbox with the new version: https://codesandbox.io/p/sandbox/mystifying-margulis-xqzr6d
