### ISSUE TITLE
Can one use the user-requested dark mode setting (prefers-color-scheme)?

### ISSUE THREAD

**Issue by altano** [code-hike/bright#22]
Customizing the `lightSelector` config option is the only way to switch between light/dark mode, right?

There's no way to make the switch happen automatically with [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), right? To just use the OS setting?

**Comment by altano** [comment]
I guess, since I'm going to add a light/dark toggle button to my site, I can't rely directly on `prefers-color-scheme` anyway, and I need to add a class to the root to reflect the potential user preference.

So I guess just go ahead and ignore this question.

**Comment by alexchantastic** [comment]
I'm actually looking for this exact functionality.

**Comment by manovotny** [comment]
I am too. Any ideas, @pomber?
