### ISSUE TITLE
dark mode with html.class dont working

### ISSUE THREAD

**Issue by tarcisioandrade** [code-hike/bright#32]
I'm using bright in a project where dark mode is done by adding the "dark" or "light" class to the html, but bright isn't following the project's theme. At the moment it only works if I add a data-theme.

**Comment by pomber** [comment]
I used Bright with `html.light` yesterday and it worked. Can you share how are you using it?

**Comment by tarcisioandrade** [comment]
> I used Bright with `html.light` yesterday and it worked. Can you share how are you using it?

I did it according to the documentation:

```
import React from "react";
import { Code as BrightCode } from "bright";

type Props = {
  code: string;
  language?: string;
  filename?: string;
};

BrightCode.theme = {
  dark: "material-palenight",
  light: "material-lighter",
};

const Code = ({ code, language, filename }: Props) => {
  return (
    <BrightCode
      code={code}
      title={filename}
      lang={language}
      style={{ margin: "48px 0 80px 0" }}
      className="[&>pre]:xl:!px-4 xl:!ml-[-32px]"
    />
  );
};

export default Code;

```

![image](https://github.com/code-hike/bright/assets/61153830/270faa4b-5223-43f1-9e49-3b5b3d1fc1c0)

**Comment by pomber** [comment]
Try adding `lightSelector` to the theme object:

```js
Code.theme = {
  dark: "material-palenight",
  light: "material-lighter",
  lightSelector: 'html.light'
}
```

**Comment by tarcisioandrade** [comment]
> Try adding `lightSelector` to the theme object:
> 
> ```js
> Code.theme = {
>   dark: "material-palenight",
>   light: "material-lighter",
>   lightSelector: 'html.light'
> }
> ```

OMG! It worked perfectly, and now I've realised that in the doc it shows this "lightSelector" property, but it was in a comment and I didn't notice it. Sorry for my stupidity and thanks for your help!
