### ISSUE TITLE
Getting bright to work with getStaticProps

### ISSUE THREAD

**Issue by DavidWells** [code-hike/bright#33]
Hello there. I like this library and the docs site is great.

I'm trying to use this in a next.js site using `getStaticProps` but it doesn't seem to work. 

```
'server-only' cannot be imported from a Client Component module. It should only be used from a Server Component.
```

Is there a reason this wouldn't work when a static next site is being generated? Previously I was using rehype/remark which is all "server-side" JS and it works fine via `getStaticProps`

Is there something special going on with the renderer or could it be used 1 off during builds inside a `getStaticProps` function

Thanks.

**Comment by pomber** [comment]
Hi, it was made for server components, it won't work with `getStaticProps`.

If you need to "manually" syntax highlight in `getStaticProps` you can try the library behind Bright: https://github.com/code-hike/lighter. But, if possible, I would recommend either moving to the App Router or keep using Remark (if you have markdown/mdx).
