### ISSUE TITLE
CSS variables in theme

### ISSUE THREAD

**Issue by pacocoursey** [code-hike/bright#41]
Is there a way to use CSS variables in the theme definition?

**Comment by pomber** [comment]
Yes, we have (undocumented) support.

You can do this for example:

```jsx
<Code lang="py" theme="material-from-css">print("hello brightness")</Code>
```

With [this CSS](https://github.com/code-hike/lighter/blob/main/lib/themes/material-from-css.css).

It uses the same themes as Code Hike so there's [more info here](https://codehike.org/docs/themes#lightdark-mode).

**Comment by pacocoursey** [comment]
Thanks, works for me!
